### PR TITLE
fix login modal and react refs

### LINKED ISSUE #60: Can't login
I'm getting a `TypeError: n.getValue is not a function` when clicking the Save button in the sign-in dialog. I suppose that refers to [this line](https://github.com/philschatz/gh-board/blob/cac40c5/src/components/login-modal.jsx#L15). I'm using Firefox 50.1.0 on OS X 10.10.5, if that helps.

### PR DESCRIPTION
**Pull request by philschatz**
fixes #60 

Facebook changed which element was attached to `this.refs` and also deprecated using `this.refs` in favor of the following syntax:

https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute

### CODE REVIEW

File: src/components/app/filter-dropdown.jsx [hunk 1]
```diff
@@ -28,8 +29,7 @@ const FilterCategory = React.createClass({
     });
   },
   onFilterInputChange() {
-    const {filterInput} = this.refs;
```
Comment (mathieudutour) [inline src/components/app/filter-dropdown.jsx]: it's probably better to use `event.target.value` instead of doing a DOM lookup (and no need for refs that way ;) )
